name: spot
description: Chainable finders and better assertions for powerful widget tests.
version: 0.1.0-preview.2
repository: https://github.com/passsy/spot
issue_tracker: https://github.com/passsy/spot/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  checks:
    git:
      url: https://github.com/dart-lang/test.git
      path: pkgs/checks
      ref: master
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.20.0

dev_dependencies:
  lint: '>=1.0.0 <3.0.0'
